name: Compile Java
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile
        run: |
          mkdir -p lib
          # ライブラリをダウンロード
          curl -L https://repo1.maven.org/maven2/org/java-websocket/Java-WebSocket/1.5.3/Java-WebSocket-1.5.3.jar -o lib/Java-WebSocket.jar
          # 依存関係を含めてコンパイル
          javac -cp "lib/Java-WebSocket.jar" OldMaidApp.java
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 # 最新版に変更
        with:
          name: class-files
          path: "*.class"
